version: "2"
services:
    frontend:
        container_name: taskmanager_web
        build:
            context: ./
            dockerfile: Dockerfile
        image: namrata/taskmanager_web
        ports:
            - "4200:4200"
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
    backend:
        container_name: taskmanager_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: namrata/taskmanager_server
        ports:
            - "4000:4000"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
